### ISSUE TITLE
Add the basic details to fork and setup the project

### ISSUE THREAD

**Issue by debidattasuryaprakash** [debidattasuryaprakash/Practicant_main#10]
Update the README.md

**Comment by Abhishekchauhan089** [comment]
Hey @debidattasuryaprakash. Can you please assign me this task. I'll work on it

**Comment by debidattasuryaprakash** [comment]
@Abhishekchauhan089 this issue has been fixed by @PRITIPADMA, so it will be closed now

**Comment by Abhishekchauhan089** [comment]
Alright @debidattasuryaprakash . Thanks
